- form-preflight/main.js
- form-preflight/package.json
- form-preflight/vite.config.js
- plugin/dev.js
- plugin/src/_preflights/tw-reset.js
- plugin/src/index.js
- pnpm-lock.yaml
- Starts adding support for 'modes'
- The `hyper` mode is just a temporary name, but is the mode that assume zero NMP infrastructure (e.g. base.css, theme.css)
> Wire up tw-reset preflight

- plugin/dev.js
- plugin/src/_rules/index.js
- plugin/src/_rules/position.js
- plugin/src/theme.js
This adds rules for various inset classes and top, left, right, bottom.
rules support the following, value suffix can of course differ, bounding will be added later.
```
inset-auto
inset-full
inset-1/2
inset-y-1
inset-x-1
top-1
left-1
right-1
bottom-1
```
All credit to @BalbinaK  for setting this up 🙌
> Add rules for inset and top, left, right bottom classes

- plugin/src/_rules/position.js
- plugin/test/position.js
Add support for global keywords to rules in position.js, as suggested in a comment from https://github.com/warp-ds/engine/pull/4#discussion_r1086772020
> Support global keywords in position rules

- plugin/DEPRECATIONS.md
This PR adds a markdown file we should populate with css classes that will probably no longer be supported in Warp Design System, or at least not in the same manner as in Fabric. We will then take a look at the full list and evaluate more in-depth how respective css rules should be handled.
Respective discussions on Slack:
- [about outline](https://sch-chat.slack.com/archives/C04LG5UTCTT/p1675342464480159)
- [about shadows](https://sch-chat.slack.com/archives/C04LG5UTCTT/p1675345388121489)
> Add outline and shadow classes to DEPRECATIONS.md

- plugin/checkFabricClasses.js
- plugin/src/_rules/border.js
- plugin/src/_rules/index.js
- plugin/src/theme.js
- plugin/test/__snapshots__/border.js.snap
- plugin/test/border.js
This adds rules for border and rounded classes, by the looks of it the added rules removes any related classes from the output of `checkFabricClasses.js`
> feat: add rules for border and rounded

- README.md
Minor change, change to correct path to parity in docs 🤷
> docs: correct relative path to parity

- DEPRECATIONS.md
- src/_rules/decoration.js
- src/_rules/index.js
- test/__snapshots__/decoration.js.snap
- test/decoration.js
Adds rules for `underline` `no-underline` and `line-through` decoration classes. 
Adds `decoration-slice` and `decoration-clone` to `DEPRECATIONS.md`
> feat: add rules for text decoration

- src/_rules/focus-ring.js
- src/_rules/index.js
- test/focus-ring.js
This adds rules for `focusable` classes which sets `outline` css
> feat: add rules for focus-ring classes

- src/_rules/gap.js
- test/gap.js
Gap is only to support values being defined in theme 💡
> fix: only support gap from theme

- DEPRECATIONS.md
- dev.js
- src/_rules/aspect-ratio.js
- src/_rules/index.js
- src/_rules/internal.js
- src/_rules/size.js
- src/_utils/handlers/handlers.js
- test/__snapshots__/aspect-ratio.js.snap
- test/__snapshots__/internal.js.snap
- test/aspect-ratio.js
- test/internal.js
- Add aspect ratio in a more ergonomic and TW-ish way: e.g. `aspect-16/9` instead of `aspect-w-16 aspect-h-9`
- Drop support for `aspect-none`, only one team was using it - the same effect should be doable using our improved support for breakpoints - e.g. `lt-sm:aspect-16/9` instead of `aspect-16/9 sm:aspect-none`
- Set up first internal classes, not sure if it might be better to include what they target, but we can fix that later - e.g. we might want `i-text-c-$foo` so we know it targets color instead of just `i-text-$foo`. Because we're only reading straight from a CSSvar with all these rules we can't really make 'smart' rules that change behavior based on some pattern.
> Backport aspect ratio, set up the first internal classes

- README.md
- package.json
- src/plugin.js
- src/postprocessor.js
- test/general.js
This creates support for an array of classes (like our component classes) to be passed to the plugin and then blacklisted from the resulting CSS.
> Wire up externalization of 'core' classes

- src/_rules/display.js
- test/__snapshots__/display.js.snap
- test/display.js
@BalbinaK raised an interesting question about the reason for supporting whatever value to be provided as an arbitrary value for the display property. This PR removes fallback to any value provided for display and improves tests and rule a bit.
Let's discuss and see if this change make sense 🙌
> Restrict arbitrary values for display

- .gitignore
- src/plugin.js
- src/postprocessor.js
- test/general.js
Separate PR to avoid pollution in other PRs :) Might help if we set up formatting on save in our IDEs. 
The following fixes it in VSCode
In `.vscode/settings.json`:
```
{
"editor.codeActionsOnSave": {
"source.fixAll.eslint": true
},
"eslint.validate": ["javascript"]
}
```
> Fix linting on unformatted files

- README.md
- dev.js
Before we could run `node dev.js 'gap-2'` to get the output like(default to rem) 👇 
```
/* layer: default */
.gap-2{gap:0.2rem;}
```
We still can do the above but now we can also provide an option with `--` prefix to use it in the theme. More info in the README
Like that(use pixels instead of rem) -> `node dev.js --usePixels --cliClasses '-m-2! gap-2'`
```
/* layer: default */
.gap-2{gap:2px;}
```
More usages: `node dev.js --usePixels --development --cliClasses '-m-2! gap-2'`
> Add support for providing options from terminal

- src/_rules/size.js
- src/theme.js
- test/__snapshots__/size.js.snap
- test/size.js
This PR adds support for arbitrary values for (max/min-)width/height classes.
Examples:
- `min-w-[400]`, 
- `min-w-[40rem]`,
- `max-h-[400]`, 
- `max-h-[400px]`,
- `w-[70]`, 
- `h-[70]`,
- `h-[70px]`,
- `h-[7rem]`
The number values default to `rem` but we also support generating values in `px` based on`theme.usePixels` boolean.
> Feat/add rules for arbitrary values for (max/min-)width/height

- src/_rules/border.js
- src/theme.js
- test/__snapshots__/border.js.snap
- test/border.js
Inspired by: https://tailwindcss.com/docs/divide-width
Added support for `divide-x|y-{0-8}-{reverse} > * + *`
Arbitrary values are not supported yet, will create a separate task for it.
> Rules and tests for divide border

- test/_helpers.js
- test/flex.js
- test/grid.js
- test/line-clamp.js
It doesn't feel necessary to have this function anymore. No need for double iteration imho either.
This PR addresses [this comment](https://github.com/warp-ds/drive/pull/60#discussion_r1121463008) as well.
Does these changes make sense?
> Remove helper function for array creation, feels unnecessary

- package.json
- pnpm-lock.yaml
- test/__snapshots__/aspect-ratio.js.snap
- test/__snapshots__/background.js.snap
- test/__snapshots__/behaviors.js.snap
- test/__snapshots__/border.js.snap
- test/__snapshots__/color.js.snap
- test/__snapshots__/decoration.js.snap
- test/__snapshots__/display.js.snap
- test/__snapshots__/grid.js.snap
- test/__snapshots__/internal.js.snap
- test/__snapshots__/line-clamp.js.snap
- test/__snapshots__/list.js.snap
- test/__snapshots__/position.js.snap
- test/__snapshots__/size.js.snap
- test/__snapshots__/space-margin.js.snap
- test/__snapshots__/static.js.snap
- test/__snapshots__/table.js.snap
- test/__snapshots__/transform.js.snap
- test/__snapshots__/transition.js.snap
- test/__snapshots__/variants.js.snap
- test/general.js
We recently saw a bug resolved in how Uno handled `'` when parsing HTML. Good to add a test for this.
> Bump deps, add test for Uno's HTML parser

- .github/workflows/release.yml
- .releaserc.json
Add `beta` and `next` to the release workflow in case we decide to name the prerelease branch something else, like they did in [eik plugin for semantic-release](https://github.com/eik-lib/semantic-release/blob/master/.github/workflows/publish.yml#L7-L9).
> chore: add beta and next branches to prereleases

- package.json
- pnpm-lock.yaml
- src/_preflights/tw-reset.js
- vite.config.js
- Bumps deps, specifically Vite 4.2 which adds support for subpath imports
- Fixes a bad comment syntax in the preflight
> fix: bad comment syntax in preflight

- src/_rules/color.js
- test/__snapshots__/color.js.snap
- test/background.js
- test/color.js
Added more bg color options as they are needed for e.g. button component
> fix: add bg color options 

- src/_rules/border.js
Removed rules that target classes like `roundedt-2` or `roundedbl-4`.
`[/^rounded-([rltb]+)(?:-(.+))?$/, handlerRounded]` targets all rounded classes we need to target.
> chore(border): remove redundant rounded rule

- src/_rules/internal.js
- test/__snapshots__/internal.js.snap
- test/internal.js
We've had rules for border width and style for different sides (top/right/bottom/left) and now we also have rules for internal classes that target color of those borders.
> feat(internals): add rules for border-top/right/bottom/left-color classes

- src/_preflights/forms/form-elements.js
As we are now styling input in component classes we do not need preflight changes for input
Short discussion about it here: https://sch-chat.slack.com/archives/C050N3NQ204/p1681292111049479
> fix: remove input related stuff from preflight

- src/_rules/size.js
- test/size.js
Rules like `h32` were matching, which makes it so both `h-32` and `h32` would have the same effect - and it would be ideal to have 'one true way' of writing these.
Slightly worse, Fabric has `h1`, `h2`, and `h3` (f.ex), and this matching would cause these to temporarily look very broken as users migrate.
> fix: height and width shouldn't match without a dash

- src/_rules/color.js
- test/__snapshots__/color.js.snap
- test/color.js
We needed to add a rules for https://github.com/fabric-ds/css/blob/49b07c05686ef132b203026e941bf04dbab6fc7a/src/components/form-elements.css#L14 to be able to add `caret-color`.
!Also changed old tokens after the renaming!
> fix: add rules and tests for caret

- src/_rules/focus-ring.js
- test/focus-ring.js
Use correct token from the spreadsheet:
TODO is left though as the offset token is not changed, yet
> fix: add correct token for the focus ring

- src/_rules/background.js
- test/background.js
We need to add support for an arbitrary one off background image.
Mentioned [here](https://warp-ds.github.io/css-docs/background-image#arbitrary-values) and is for now needed in the toggle component
> fix: be able to use a one-off background image

- src/_rules/border.js
- test/__snapshots__/border.js.snap
- test/border.js
We need to add support for adding arbitrary values for border width. We need it for setting border-width: 6 for the toggle radios.
> fix: add arbitrary width support for border

- src/_rules/internal.js
- test/__snapshots__/internal.js.snap
- test/internal.js
Generate box-shadow css for component classes that rely on component-specific shadow tokens.
> feat(internals): add rules for shadow component classes

- src/_rules/shadow.js
- test/__snapshots__/shadow.js.snap
Added Finn shadow values as default to generic shadow rules based on [this thread](https://sch-chat.slack.com/archives/C050N3NQ204/p1682607264763969?thread_ts=1682339766.883849&cid=C050N3NQ204).
> fix(shadows): add default box-shadow values to generic shadow classes

- package.json
- src/_preflights/index.js
- src/_preflights/typography.js
- src/_rules/index.js
- src/_rules/typography.js
- src/_shortcuts/index.js
- src/_shortcuts/typography.js
- src/_utils/mappings.js
- src/internals.js
- src/plugin.js
- test/__snapshots__/typography.js.snap
- test/size.js
- test/typography.js
This PR adds rules for typography-related classes that rely on font-size and line-height tokens coming from the theme css file (or preflight css):
- add rules for `text-{number}`, `text-{t-shirt-size}`, `leading-{number}`, `leading-{t-shirt-size}`
- add aliases for the above classes, like `h1`, `t1`, `text-body` using [unocss shortcuts](https://github.com/unocss/unocss/blob/main/docs/config/shortcuts.md)
- define default values for font-size and line-height CSS variables in Preflight, so it's possible to use the above rules without setting theme-specific typography tokens
Before:
After:
> feat(rules): add typography rules

- src/_rules/index.js
- src/_rules/slider.js
- test/__snapshots__/slider.js.snap
- test/slider.js
This PR includes hard coded classnames for the slide thumb. 
The current solution is not supported by theming, and has the same color for all themes. 
The difference from fabric is that the shadow is gray instead of blue.
> feat(slider): add border shadow for active and hover states

- src/_rules/slider.js
- test/__snapshots__/slider.js.snap
- test/slider.js
This PR includes:
- Remove one too many parentheses for `sliderHandleShadow` 
- Add styling specific for the `slider`: removes the outline of the thumb
> fix(slider): fix slider bug

- src/_rules/static.js
- test/__snapshots__/static.js.snap
- test/static.js
While migrating styles for the modal the need of adding the safe inset appeared. 
Here are two code examples 👇 
https://github.com/fabric-ds/css/blob/next/src/components/modal.css#L16
https://github.com/fabric-ds/css/blob/01fd80a27461cf0d593911e974853f84963d0681/src/components/toast.css#L3
I couldn't find any suitable rule in unocss, only custom plugins. So I ended up creating our own rules. For the naming I got inspired by [this plugin](https://github.com/mvllow/tailwindcss-safe-area)
Wdyt?
> feat: rule for adding safe area inset from the bottom edge of the viewport

- src/_preflights/tw-reset.js
Font-scaling #issue
Rem sized fonts always reference whatever is set on the html tag, in most cases the html will have the same warp reset and will work fine, but what do we do in cases where we are trying to run a warp thing in shadow dom on templates that are NOT warp ?   
If template runs Fabric:   
In theory we could release fabric with a patch that just sets the html reference to 62.5% and it shouldn’t affect the rest of the site since fabric is set up with locked down px sizes. (A quick test on finn.no front-page showed one single text affected by adding that)
On Other sites:
We need to look into how these works case by case. 
If Rems are in use for font-scaling and is scaling differently than 62.5% then it will prob be a world of pain.
This fix in this PR addresses problem with …
> fix: restructure html and body styling to make shadow dom styling work

- src/_preflights/tw-reset.js
I could reproduce issue in Firefox [here](https://warp-ds.github.io/tech-docs/components/checkbox/) and then in local Vue setup
Expected|What we got|Fixed
---|---|---
> fix: improve syntax to clear the float for the elements after legend

- src/_rules/focus-ring.js
- test/focus-ring.js
Migrated fabric stuff from https://github.com/warp-ds/drive/blob/alpha/src/_rules/focus-ring.js but didn't work as we wished.
Before|After
---|---
> fix: focusable classes

- src/_rules/background.js
- test/background.js
The rule should cover both image and colors.
So if we have `url` in an arbitrary value then it is a `background-image` (https://unocss.dev/interactive/?s=bg-[url(hej)])
If it is `var` or not then it is `background-color` (https://unocss.dev/interactive/?s=bg-[var(hej)] or https://unocss.dev/interactive/?s=bg-[hej])
> fix: improve arbitrary bg rule

- src/_shortcuts/index.js
- src/_shortcuts/pageContainer.js
- src/theme.js
New shortcut for `page-container`. Styles moved from https://github.com/fabric-ds/css/blob/01fd80a27461cf0d593911e974853f84963d0681/src/components/page-container.css#L1. More info in the ticket linked
Tested in Vue|>1300px|<1300px
---|---|---
Tested in Vue|![image](https://github.com/warp-ds/drive/assets/37986637/13ae6c8f-ea0a-4ad9-baac-0c6afa97b7b6)|![image](https://github.com/warp-ds/drive/assets/37986637/46b432e9-23b9-49b8-a355-e37528342686)
> feat: add new shortcut for page-container

- src/_rules/index.js
- src/_rules/semantic.js
- src/_utils/handlers/handlers.js
- test/__snapshots__/semantic.js.snap
- test/semantic.js
The idea is to give consumers access to semantic variables to set background, border and text colors.
Using the class `s-bg-default` would give the following css: `background-color: var(--w-s-color-background-default);`
`s-border-positive-default` would give: `border-color: var(--w-s-color-border-positive-default);`
(also including support for directions [lrtbxy], e.g. `s-border-x-positive-default`)
and `s-text-link-hover` would give: `color: var(--w-s-color-text-link-hover);`
...based on the tokens added in this PR: https://github.com/warp-ds/tokens/pull/73
> feat: Add background, text and border classes for semantic color tokens

- src/_rules/border.js
- test/__snapshots__/border.js.snap
- test/border.js
`border-transparent|inherit|current`
(plus some minor refactoring/merging of the regex rules)
> fix: Added missing rules for static border colors 

- src/_rules/index.js
- src/_rules/outline.js
- test/__snapshots__/outline.js.snap
- test/outline.js
New rules for outline based on:
- https://tailwindcss.com/docs/outline-width
- https://tailwindcss.com/docs/outline-style
- https://tailwindcss.com/docs/outline-offset
With `outline-none` now added we can remove https://github.com/warp-ds/drive/blob/alpha/src/_rules/slider.js#L20. Will create a ticket for it
TBD: I'll update the css docs with this new rules
> feat: add rules for outline

- src/_rules/background.js
- test/background.js
[This refactoring](https://github.com/warp-ds/drive/pull/111) broke the check mark icon for the checkboxes. We needed one more check for the vars as urls.
Before|After
---|---
This PR is needed to make everything work https://github.com/warp-ds/component-classes/pull/89. I tested locally, link local builds for drive and cc in vue
> fix: proper handle bg arbitrary url as var

- src/_rules/color.js
- test/__snapshots__/color.js.snap
- test/color.js
Removed old bg and text color classes that has been replaced with semantic equivalents and aligned text color classes with border and bg classes
> fix: Cleanup color classes for text and background color

- src/_rules/slider.js
- test/__snapshots__/slider.js.snap
- test/slider.js
After https://github.com/warp-ds/drive/pull/125 we do not really need the custom class created only for slider.
Usage of the custom class is removed [here](https://github.com/warp-ds/component-classes/pull/94)
> fix: remove a shortcut for the outline-none

- src/_rules/size.js
- src/_rules/typography.js
- src/_utils/utilities.js
- test/__snapshots__/typography.js.snap
- test/typography.js
Almost all buttons are using `leading-24` . The class is also used in one place in finn. 24 - is not a part of our tokens so we need to support arbitrary values here. (more info about the discussion [here](https://sch-chat.slack.com/archives/C050N3NQ204/p1686921532451109))
We have also one usage of the custom line-height https://github.com/fabric-ds/css/blob/49b07c05686ef132b203026e941bf04dbab6fc7a/src/components/form-elements.css#L176 that we will be able to set with this support.
> feat: arbitrary values accepted for leading

- src/_preflights/resets.js
The `getCSS` function runs every time the plugin is doing a build - which when developing locally is _often_.
Caching the CSS here means our servers will serve less data, and also the local development experience will be sped up by however long this download would have taken; meaning if this download would ever experience issues the user's dev-env would hang for unknown reasons to them!
> fix: cache the preflight instead of requesting every rebuild

- src/_preflights/resets.js
Top-level await was causing issues when used client-side (e.g. the playground)
> fix: avoid top-level await in reset

- README.md
- dev.js
- package.json
- pnpm-lock.yaml
- src/plugin.js
- test/_helpers.js
- vite.config.js
As we are publishing the component.css to EIK our consumers do not need to safelist the classes anymore. They can use the css directly from EIK. Benefits: cached css instead of every app safelists the classes. Could be added to the template etc
And as we don't want duplicated styles to be generated we can finally use `externalizedClasses` and postprocess feature. For that I needed a flag and I took back `development` flag that we removed when we thought that preflight was the only feature that that flag controlled.
When this one is merged we will need to update https://github.com/warp-ds/playground/blob/b1584b611bc0cdb9b98cb10a576bc49bb4105f11/src/css.js#L9 and use the `development` flag instead
> fix: add development flag back and externalize our published component classes

- src/_rules/focus-ring.js
- test/focus-ring.js
Needs added token from: https://github.com/warp-ds/css/pull/19
> fix: Update focus outline to use new semantic color token

- src/_rules/shadow.js
- test/__snapshots__/shadow.js.snap
Removing old hard coded fallback values for box-shadows as discussed here: https://sch-chat.slack.com/archives/C050N3NQ204/p1688047940344899
> fix: Remove old fallback values from box shadows

- src/_rules/border.js
- src/_rules/typography.js
[WARP-121](https://nmp-jira.atlassian.net/browse/WARP-121): Add `tabular-nums`, `lining-nums` and `border-inverted` (to replace `border-white` ) + some font variant numeric classes from tailwind.
Other notes: 
* PR to update parity with these findings: https://github.com/warp-ds/parity/pull/3
* New working document to investigate the classes: https://docs.google.com/spreadsheets/d/1W0n74LSV6IG2YIU1LJNopFNtTkSYLY3rfPa9c1qg9d4/edit#gid=0
* We also had this from earlier: https://docs.google.com/spreadsheets/d/1gk1LhpUimjk9QnZhZyId7c56xk30dbzQxRCzuGLlllY/edit#gid=0
> fix: add missing classes Fabric supported

- dev.js
- package.json
- pnpm-lock.yaml
- src/plugin.js
Now that we have own new css repo which contains component-classes we need to update dependencies and imports
> fix: use new css repo for component classes

- src/_rules/display.js
- test/__snapshots__/display.js.snap
The order of CSS for display classes is now aligned with [fabric.css](https://assets.finn.no/pkg/@fabric-ds/css/1.2.0/fabric.min.css) that Warp should be based on. This fixes e.g. issues with `flex` class not overriding any other default display style of a given element, like it used to in Fabric.
> fix(display.js): align order of css for display classes with fabric.css

- package.json
- pnpm-lock.yaml
- src/_preflights/resets.js
- test/__snapshots__/internal.js.snap
- test/general.js
- test/internal.js
When latest (0.55.0) `unocss` package version was installed, an error was thrown from a lower version of `@unocss/core`:
```
import { escapeSelector, createValueHandler, isString, escapeRegExp, CountableSet, BetterMap } from '@unocss/core';
^^^^^^^^^^^^
SyntaxError: The requested module '@unocss/core' does not provide an export named 'CountableSet'
at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
```
Aligning the two dependencies in this PR fixes the error but some tests had to be slightly adjusted, too.
By the way, `@warp-ds/css` was updated to `1.0.0-alpha.37` and a deprecated `resets.min.css` file was replaced with `resets.css`.
> fix: update & align unocss dependencies

- README.md
- dev.js
- package.json
- pnpm-lock.yaml
- src/plugin.js
- test/__snapshots__/external-classes.js.snap
- test/external-classes.js
`@warp-ds/css` dependency was only used to import component classes array and “externalize” those to avoid generating redundant CSS when it’s already available in an app through [components.css](https://assets.finn.no/pkg/@warp-ds/css/v1/components.css).
Until we figure out how to fix externalizing of component classes in a better way, we remove the option `omitComponentClasses` from the plugin. The users will then need to import the `@warp-ds/css` package and pass the imported component classes array to `externalClasses` option of `presetWarp` to achieve the same goal.
> fix: remove @warp-ds/css dep to fix circular dependency

- src/_rules/aspect-ratio.js
- test/__snapshots__/aspect-ratio.js.snap
- test/aspect-ratio.js
fixes #116 
Aspect ratio support is currently provided via the ['padding-bottom'](https://css-tricks.com/aspect-ratio-boxes/) fallback method. The built-in `aspect-ratio` property is not yet well supported, but for `aspect-ratio` utility class I couldn't find a better way to handle it than by generating this CSS: `.aspect-ratio { aspect-ratio: auto; }`.
> fix(aspect-ratio): add rules for aspect-ratio, -video and -square

- package.json
- pnpm-lock.yaml
More on the issue here: https://github.com/warp-ds/drive/security/dependabot/6
> fix: update vite to 4.2.3 to fix a vulnerability

- .github/workflows/release.yml
- .github/workflows/update-next.yml
- .releaserc.json
- CONTRIBUTING.md
- README.md
- dev.js
Changes included:
- Add `CONTRIBUTING.md`
- update github workflows to use `next` instead of `alpha`
- update `README.md` with instructions on contribution to align with other Warp packages
> chore: set next as prerelease branch

- DEPRECATIONS.md
- src/_rules/backdrop.js
- src/_rules/index.js
- test/__snapshots__/backdrop.js.snap
- test/backdrop.js
New rules for backdrop-blur based on:
https://tailwindcss.com/docs/backdrop-blur
(though the blur sizes has been modified and also size names are changed to align with how it is in warp)
> feat: Add rules for backdrop-blur

- src/_variants/index.js
- test/__snapshots__/variants.js.snap
- test/variants.js
Add `variantPartClasses` to _variants
**Note:** This is part of implementing changes to the expandable-component in the elements-repo in order to be able to style the svg from a warp-icon that is inside a shadow-DOM using the [CSS pseudo-element part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) that is also supported by unoCSS.
> feat: add variantPartClasses to _variants

- src/_rules/focus-ring.js
- src/_rules/semantic.js
- test/__snapshots__/semantic.js.snap
- test/focus-ring.js
- test/semantic.js
Fixes [WARP-398](https://nmp-jira.atlassian.net/browse/WARP-398):
We should allow users to style the color of the outline in the same way as they can style border - using semantic color classes. We can for the time being reuse border color tokens, but since the focused outline color is currently assigned to a generic `--w-s-color-focused` token, we thought it’s better to have it as  `--w-s-color-border-focused` to make the border and outline color rules aligned. 
We're keeping the generic `--w-s-color-focused` token for backward compatibility, but we can indicate that it may be removed by setting the `--w-s-color-border-focused` on `focusable` with the previous CSS variable as fallback. I'm open to solving it in a different way. We haven't really spoken about the future of …
> feat(rules): add support for outline color classes

- src/_rules/background.js
- src/_rules/border.js
- src/_rules/color.js
- src/_rules/focus-ring.js
- src/_rules/outline.js
- src/_rules/semantic.js
- test/__snapshots__/background.js.snap
- test/__snapshots__/border.js.snap
- test/__snapshots__/color.js.snap
- test/__snapshots__/outline.js.snap
- test/__snapshots__/semantic.js.snap
- test/background.js
- test/border.js
- test/color.js
- test/outline.js
- test/semantic.js
- Add support for css variables in arbitrary values for border and divide
- Add support for css variables in arbitrary values for text
- Add support for color and css variables in arbitrary values for outline
- Add support for semantic classes setting divide color
Co-authored by: @Skadefryd
> feat: Add missing support for arbitrary and semantic colors

- src/_rules/layout.js
- src/_rules/position.js
- src/_rules/transition.js
- src/_utils/handlers/handlers.js
- test/__snapshots__/layout.js.snap
- test/__snapshots__/position.js.snap
- test/__snapshots__/transition.js.snap
- test/layout.js
- test/position.js
- test/transition.js
Fixes JIRA ticket: [WARP-413](https://nmp-jira.atlassian.net/browse/WARP-413)
- Adjust rule for order to only accept 1-12, and add support for arbitrary values for order following the unit-less convention, for example: `order-[14]`
- Add support for columns (accept 1-12), as well as, support arbitrary values for columns, following the unit-less convention, for example: `columns-[13]`
- Add support for arbitrary values for transition-timing function, following a unit-less convention together with `cubic-bezier`, for example: `ease-[cubic-bezier(0.95,0.05,0.795,0.035)]`
- Add tests for order, columns and transition-timing
> feat: support arbitrary values for order, columns and transition-timing

- src/_rules/border.js
Fixes handling of all types of supported arbitrary values for `border` and `divide`
- Values starting with `--` will be setting border-color (transcribed as `var(--...)`)
- Values added as `var(...)` will set `border-color`
- Values added as numbers followed by optional unit will set `border-width`
- Any other arbitrary values will set `border-color` (e.g. "#000000", "black", "rgb(0,0,0)", "asdfasdf"...)
This should also work with any valid direction ([lrtbxy] for border, [xy] for divide).
> fix: Improve arbitrary values handling for border and divide

- src/_rules/background.js
- test/__snapshots__/background.js.snap
- test/background.js
(...and some minor background rules cleanup)
> feat: Add rule for setting background-image to none

- src/_rules/background.js
- src/_rules/border.js
- src/_rules/color.js
- src/_rules/outline.js
- src/_utils/utilities.js
- test/__snapshots__/background.js.snap
- test/__snapshots__/border.js.snap
- test/__snapshots__/color.js.snap
- test/__snapshots__/outline.js.snap
- test/background.js
- test/border.js
- test/color.js
- test/outline.js
Adds support for an optional alpha channel modifier to arbitrary color classes (e.g. `bg-[--w-s-border-primary/50]`, `border-[var(--w-black)/25]` ...).
> feat: Add support for alpha channel modifier to arbitrary color classes

- src/_rules/semantic.js
- test/__snapshots__/semantic.js.snap
- test/semantic.js
https://nmp-jira.atlassian.net/browse/WARP-503
> feat: New surface concept

- src/_rules/static.js
- test/__snapshots__/static.js.snap
Adds missing rules for: https://warp-ds.github.io/css-docs/break-inside#setting-the-break-inside-behavior
Reported here: https://sch-chat.slack.com/archives/C04P0GYTHPV/p1713167639919199
> feat: Added rules for break-inside

- src/_rules/spacing.js
- src/_utils/utilities.js
- test/__snapshots__/spacing.js.snap
- test/spacing.js
CSS variables are now valid arbitrary values for padding and margin. This will allow setting a class on Warp TextFields with long prefixes like `pl-[var(--w-prefix-width,_40px)]`  instead of using [inline css](https://github.com/warp-ds/elements/blob/next/packages/textfield/index.js#L43-L45) or [style blocks](https://github.com/warp-ds/react/blob/next/packages/textfield/src/component.tsx#L48-L54).
Additionally, this PR contains the following changes:
- [fix: remove bracket handler from directionSize util](https://github.com/warp-ds/drive/commit/b321b389630decb6d1a902576678f241de3fe42a) - `bracket()` handler for matching arbitrary values was removed from `directionSize` util as we are handling all arbitrary values as separate rules now. This helped specify more strict arbitrary rules, as …
> feat: support css vars as arbitrary values for margins and paddings

- src/_rules/list.js
- test/list.js
Tweak positioning of list-checked icon to work as good as possible with different font-sizes/line-heights.
Reported here: https://nmp-jira.atlassian.net/browse/WARP-512?focusedCommentId=224873
> fix: Tweak positioning of list-checked icon

- src/_rules/typography.js
- test/__snapshots__/typography.js.snap
- test/typography.js
Added missing rule for setting line-height to 1:
`.leading-none:{line-height:1}`
> feat: Added leading-none rule to set line-height to 1

- package.json
- pnpm-lock.yaml
Hey gang.
[Uno 0.65.0](https://github.com/unocss/unocss/releases/tag/v0.65.0) has a breaking change which affects us. With the dependencies as they are now we end up with the latest `0.x` by default. It's not semver stable, so this PR pins the unocss version to the last known working version.
> fix: pin to uno 0.64.1
