.github/workflows/test.js.yml, plugin/src/_utils/colors.js, plugin/src/_utils/getComponents.js, plugin/src/_utils/index.js, plugin/src/_utils/utilities.js, plugin/src/_utils/variants.js
https://trello.com/c/uao1awUR/31-engine-fix-circular-dep
=> Fix circular dependencies

plugin/dev.js, plugin/src/_rules/index.js, plugin/src/_rules/position.js, plugin/src/theme.js, plugin/test/general.js, plugin/test/position.js
This adds the rules to remaining position-related classes, i.e. position, float-, clear-, z- and box- classes, which makes it possible to generate respective styles.
=> Feat: add rules for position, float, clear, z-index and box-sizing

plugin/test/align.js
As title says, this adds tests for the allowed classes defined in `rules/align`.
=> feat: add tests for align rules

plugin/src/_rules/index.js, plugin/src/_rules/layout.js, plugin/test/layout.js
This adds layout rules to the engine, layout rules exposes the posibility to generate css from using `overflow-, overflow-x- and overflow-y-` classes. Values can be set to `auto, hidden, visible, scroll`.
👇 
```
overflow-auto
overflow-x-visible
overflow-y-hidden
overflow-scroll
```
=> feat: add layout rules and tests for rules

plugin/checkFabricClasses.js
Small fix which changes import from non existing index to #plugin alias
=> fix: use #plugin alias in import

plugin/DEPRECATIONS.md
Based on updates in https://github.com/warp-ds/parity/commit/2bdeca1408fa68b0deff23f78e490be0ce7696e9
=> Add `ring` to deprecated.md

DEPRECATIONS.md
Add last-child to deprecations list
=> docs: add last-child to DEPRECATIONS list

src/_rules/color.js, src/theme.js, test/color.js
Background: Part of https://trello.com/c/JAeAbfHq/1-engine-add-rules-and-bounds
=> Add theme opacity and tests

src/_preflights/forms/form-elements.js
=> Add token for the input placeholder color

dev.js
=> Minor change in the classes output

src/_rules/index.js, src/_rules/list.js, test/list.js
Added list-checked class from here:
https://github.com/fabric-ds/css/blob/49b07c05686ef132b203026e941bf04dbab6fc7a/src/components/list.css
Question: Should we add fallbacks to all vars.
=> Add list-checked rule and corresponding test

src/_rules/color.js, test/__snapshots__/color.js.snap
=> Add proper styling for background-color

.github/workflows/lint.pr.yml, package.json
Prevent the need for any further lint-fix PRs by blocking anything from going in that isn't nice and tidy!
=> Add a linting check to PRs

test/__snapshots__/behaviors.js.snap, test/behaviors.js
- Add more tests for all applicable list styles
- Add test for invalid classes
=> Minor improvements on list styles tests

test/__snapshots__/background.js.snap, test/background.js
Added missing tests for `bg-clip`
=> Tests for bg clip

src/_rules/position.js, test/__snapshots__/position.js.snap, test/__snapshots__/static.js.snap, test/layout.js, test/position.js, test/static.js
=> Missing rules and tests

src/_rules/border.js, test/__snapshots__/border.js.snap, test/border.js
Align divide-*-reverse implementation with TW
https://tailwindcss.com/docs/divide-width#reversing-children-order
***TODO***
Will update docs after this fix
=> Fix divide reverse implementation

.releaserc.json
=> docs: silent the semantic bot

src/_rules/background.js, test/background.js
Before|After
---|---
.bg-\\\\[url\\\\(\\\\'\\\\/img\\\\/hero-pattern\\\\.svg\\\\'\\\\)\\\\]{background-image:url(/img/hero-pattern.svg);}|.bg-\\\\[url\\\\(\\\\'\\\\/img\\\\/hero-pattern\\\\.svg\\\\'\\\\)\\\\]{background-image:url('/img/hero-pattern.svg');}
=> fix: add missing apostrofs

src/_rules/static.js, test/__snapshots__/static.js.snap
=> feat(touch-actions): add support for touch actions

src/_rules/animations.js, src/_rules/focus-ring.js, src/_variants/index.js, src/_variants/lastChild.js, test/__snapshots__/variants.js.snap, test/animations.js, test/focus-ring.js, test/variants.js
Please check the tickets linked for more info about the fixes.
=> fix: focusable, last-child, spinner rules

.github/workflows/lint.pr.yml, .github/workflows/release.yml, .github/workflows/test.js.yml
Versions applied are based on [this Slack discussion](https://sch-chat.slack.com/archives/C050N3NQ204/p1682420782915109?thread_ts=1682412782.582729&cid=C050N3NQ204)
=> fix(workflows): set node v to lts/* and pnpm to 8

src/_rules/border.js, test/__snapshots__/border.js.snap, test/__snapshots__/slider.js.snap, test/border.js
Fixing this https://github.com/warp-ds/drive/issues/117
=> fix: border-x|y fix and slider obsolete snapshot fix

src/_shortcuts/pageContainer.js
Needed for: https://github.com/warp-ds/css/pull/16
=> fix: Replace arbitrary background class with semantic class for page-container

README.md, src/_preflights/index.js, src/plugin.js
Background: https://nmp-jira.atlassian.net/jira/software/projects/WARP/boards/15?selectedIssue=WARP-176
=> fix: add skipResets flag

src/_rules/semantic.js, test/__snapshots__/semantic.js.snap, test/semantic.js
- Support for direction in semantic divide classes
- General cleanup of the semantic rules
=> fix: Add support for direction in semantic divide classes

src/_rules/background.js, src/_rules/border.js, src/_rules/color.js, src/_rules/outline.js, src/_rules/typography.js, src/_utils/handlers/handlers.js, test/__snapshots__/border.js.snap, test/border.js
- Cleanup arbitrary background values to only match variables and urls for now
- Cleanup arbitrary border value matching and add support for units
- Better variable matching for arbitrary text colors
- Improve arbitrary outline colors to only match variables for now
- Move remaining background color handling from colors.js to background.js
- Misc cleanups
=> fix: Misc arbitrary values cleanup

src/_variants/index.js, test/__snapshots__/combinators.js.snap, test/combinators.js
Adds support for https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_variants/combinators.ts
=> feat: Add support for variant combinators

src/_rules/list.js, test/list.js
Uses this: https://github.com/warp-ds/css/pull/194
=> fix: New svg icon and styling fixes for list-checked

package.json, pnpm-lock.yaml
**Changes:**
- Update devDependencies
=> chore: update devDependencies

dev.js, eslint.config.js, package.json, pnpm-lock.yaml, src/_rules/focus-ring.js, src/_rules/table.js, src/_variants/index.js, src/_variants/lastChild.js, src/_variants/spaceAndDivide.js, test/_helpers.js, test/general.js, test/size.js
So uno has changed some of it's api's.
Had to deep dive in their PR's and figure out what was going on. 
This PR helped: https://github.com/unocss/unocss/pull/4298/files
=> fix: Upgrade uno to 0.65
